//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class CommentRecord
    {
        public int CommentId { get; set; }
        public Nullable<int> CookBookId { get; set; }
        public Nullable<int> UserId { get; set; }
        public int PId { get; set; }
        public string Content { get; set; }
        public System.DateTime DateTime { get; set; }
    
        public virtual CookBook CookBook { get; set; }
        public virtual UserInfo UserInfo { get; set; }
    }
}
